# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: nodey462
  repository: file://../nodey462
